algoritmo "CalculoDelta"
var
   a, b, c, delta: Real
inicio
      Escreva("Digite o valor de a: ")
      Leia(a)
      Escreva("Digite o valor de b: ")
      Leia(b)
      Escreva("Digite o valor de c: ")
      Leia(c)
      delta <- b^2 - 4 * a * c
      Escreval("O valor de a e ", a)
      Escreval("O valor de a b ", b)
      Escreval("O valor de a c ", c)
      Escreva("O valor de delta e ", delta)
fimalgoritmo
